version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth --verbose --output=dist
artifacts:
  base-directory: dist
  files: 
    - **/*
  name: openlawnz-api
