version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth --verbose --output=dist
artifacts:
  files:
    - /**/*
  base-directory: dist
  name: openlawnz-api
